#! /bin/csh
if (-f *512x512.png) then
set fn = `echo *512x512.png | awk '{print substr($1,1,length($1)-11)}'`
pngtopam -alpha ${fn}512x512.png > alpha512.pgm
pngtopam -mix ${fn}512x512.png > rgb512.pnm
set a = 512
foreach s (256 128 64 32 16)
if (-f ${fn}${s}x${s}.png) then
  pngtopam -alpha ${fn}${s}x${s}.png > alpha${s}.pgm
  pngtopam -mix ${fn}${s}x${s}.png > rgb${s}.pnm
else
  pamscale 0.5 alpha${a}.pgm > alpha${s}.pgm
  pamscale 0.5 rgb${a}.pnm | pnmquant 2048 > rgb${s}.pnm
endif
set a = $s
end
foreach s (256 128 32 16)
if (! -f ${fn}${s}x${s}.png) then
  pnmtopng -alpha alpha${s}.pgm rgb${s}.pnm > ${fn}${s}x${s}.png
endif
@ a = $s * 2
if (! -f ${fn}${s}x${s}@2x.png) then
  pnmtopng -alpha alpha${a}.pgm rgb${a}.pnm > ${fn}${s}x${s}@2x.png
endif
end
rm alpha*.pgm rgb*.pnm
endif
